### ISSUE TITLE
Some errors in scripts

### ISSUE THREAD

**Issue by Ra1nyHouse** [yangji9181/PACE2017#1]
I find some errors in your scripts.
First one is in download_data.sh(#9 and #12). 
Running this scipt will download visited_spots.txt twice.

Second one is in dataset.py(#300).
The code `path.append(graph_dict.keys()[random.randrange(len(graph_dict))])` will cause some exceptions using python3.6.

**Comment by HermiteBai** [comment]
Error 2 didn't happen on my machine while using Python 3.6, can you also provide more details about the exception you mentioned?

**Comment by Ra1nyHouse** [comment]
I remove inter_small.pkl, test_small.pkl and traindata_small.pkl, 
and run `python dataset.py` will cause the exception:

Reading file gowalla/visited_spots.txt to construct training labels
Filtering users and spots
Traceback (most recent call last):
  File "dataset.py", line 349, in <module>
    dt = Dataset()
  File "dataset.py", line 33, in __init__
    self.generate()
  File "dataset.py", line 75, in generate
    self.user_enum, self.spot_enum = self.getCrossLabels()
  File "dataset.py", line 127, in getCrossLabels
    for user in user_dict.keys():
RuntimeError: dictionary changed size during iteration


In addition, could you please provide a evaluating script(recall@k)? thanks!
