### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by zhenql** [yangji9181/PACE2017#3]
I'm a student who am learning POI recommendation. I tried to run your program and I had download your gowalla dataset file from http://lbai5.web.engr.illinois.edu/data/ . But I find it is different from the dataset on http://snap.stanford.edu/data/loc-gowalla.html (you reference it's corresponding paper in your paper when you mention the gowalla dataset ) . One of the differences is the number of location, 2942667 in the former dataset(spot_location.txt) and 1280969 in the latter.  Why dose that happen?

**Comment by zhenql** [comment]
The second issue is the ratio of "traindata_small" to "traindata_small + testdata_small", why you set split=0.01 by default? 
The third issue is about sampling process that defines the distribution p(u_i ,u_c ,γ ) in your program. I find the var "u_context" and "s_context" in train.ipynb is very sparse, the sum of all element in u_context is 3716, 3209 in s_context, means each user have 3716/80238 context and each spot have 3209/80238 context.

**Comment by yangji9181** [comment]
1. The details of the dataset we use are described in our paper. The differences in numbers of spots, users and checkins are due to different collection periods and filtering of infrequent ones.
2. The code is to provide a walk-through of building the PACE model. Evaluation is done with training and testing data split to 8:2 according to check-in times.
3. You can tune sampling rate to achieve better performance, which also leads to different runtimes.

**Comment by zhenql** [comment]
I checked the different collection periods, 

> The Gowalla check-in dataset[7] was generated world-wide from Feb. 2009 to Oct. 2010

(paper p1250)
same to the website dataset. 
And your reference paper [7] give the website ( http://snap.stanford.edu/data/loc-gowalla.html ). 
Have not filtering.
So I think two datasets are the same. Was I wrong?
By the way, number of spots in your dataset is **more than** number in the website dataset.

I want to repeat the experiment in your paper, but I can not find the **check-in times**.

Thanks for your reply.

**Comment by yangji9181** [comment]
Hi Ranzhen,

Thanks for following up. I currently do not have the exact Gowalla dataset we used. It was provided by the authors of this paper http://www.vldb.org/pvldb/vol10/p1010-liu.pdf. We should have cited this paper, but it was not published at the time of writing our paper. Sorry about all the confusions.

**Comment by Songweiping** [comment]
Hi @yangji9181 @HermiteBai ,

Thanks for sharing this project. I have similar questions with @zhenql. The data set at http://lbai5.web.engr.illinois.edu/data/ is different from Stanford data in many ways.

First, as Ranzhen mentioned, there is no check-in timestamp in your data. So does user check-ins in visited_spots.txt ordered by time?
Second, how did you collect spot category information, which is not included in Stanford data?

Would it be convenient to provide the original data set you used at this time?
Thanks!

**Comment by yangji9181** [comment]
Hi,

Sorry for the late reply. Yes we assume check-ins are ordered by time. We did not use spot category information in this project (we claimed a general framework that is able to take such information, but in experiments we only used geographic distance to build the context graphs). Hope this helps!

Best,
Carl Yang
University of Illinois, Urbana Champaign
http://jiyang3.web.engr.illinois.edu/

**Comment by yixiazhinian** [comment]
Hi @zhenql @Songweiping ,
Sorry to bother you. I tried to download the dataset but it turned out that the website http://lbai5.web.engr.illinois.edu/data/ has already been suspended.
Would it be convenient for either of you to provide a copy of the dataset?
Thanks a lot!

**Comment by sfsafavi** [comment]
Hi @zhenql @Songweiping @yixiazhinian,
I tried to download the dataset too but it turned out that the website.
I'm so confused about original dataset.
Would it be convenient for either of you to provide a copy of the dataset?
Best regards,sadaf
